[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
cache_path = 'cache'
bytecode_hash = 'none'

[fmt]
tab_width = 4
max_line_length = 120
multiline_func_header = 'params_first'

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[profile.fork]
fork_url = "${MAINNET_RPC_URL}"
